### ISSUE TITLE
MultiValueHeaders seems ineffective

### ISSUE THREAD

**Issue by peterheb** [a-h/awsapigatewayv2handler#3]
I'm not sure if this changed on AWS's side at some point, but awsapigtewayv2handler puts headers in resp.MultiValueHeaders, which doesn't seem to work. Despite that field existing in aws-lambda-go's APIGatewayV2HTTPResponse object (??), the AWS docs currently say: *Format 2.0 doesn't have multiValueHeaders or multiValueQueryStringParameters fields. Duplicate headers are combined with commas and included in the headers field.* [(src)](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html#http-api-develop-integrations-lambda.proxy-format)

Simple test app and link (up for now) -- you can see that through Lambda, it's coming back application/json, but the content-type works fine on localhost. (This is through a Lambda Function URL, which uses the [API Gateway v2](https://docs.aws.amazon.com/lambda/latest/dg/urls-invocation.html#urls-payloads) proxy format):
https://gu4zic476njzegpu4z4dsodu3q0psopd.lambda-url.us-east-1.on.aws/smile

Also, could you assign a license to this project? It's a handy piece of code!

```
package main

import (
	"fmt"
	"net/http"
	"os"

	"github.com/a-h/awsapigatewayv2handler"
)

// SVG from Heroicons, MIT licensed: https://heroicons.com/
const smileyFace = `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
  <path stroke-linecap="round" stroke-linejoin="round" d="M14.828 14.828a4 4 0 01-5.656 0M9 10h.01M15 10h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
</svg>`

func SmileHandler(w http.ResponseWriter, r *http.Request) {
	w.Header().Add("content-type", "image/svg+xml")
	w.WriteHeader(http.StatusOK)
	w.Write([]byte(smileyFace))
}

func main() {
	http.HandleFunc("/smile", SmileHandler)
	if len(os.Getenv("LAMBDA_TASK_ROOT")) == 0 {
		fmt.Println("Listening on port 5177")
		err := http.ListenAndServe("localhost:5177", http.DefaultServeMux)
		fmt.Printf("http.ListenAndServe: %v", err)
	} else {
		awsapigatewayv2handler.ListenAndServe(http.DefaultServeMux)
	}
}
```

**Comment by a-h** [comment]
Thanks, and the quality reproduction is much appreciated too. I'll take a look into it!

**Comment by a-h** [comment]
Thanks, I've updated to use the Headers field, and ran it through the example.

<img width="875" alt="image" src="https://user-images.githubusercontent.com/1029947/178721137-666478b4-5145-43d0-b3f8-fa1abee261d7.png">

**Comment by a-h** [comment]
I've also:

* Added an MIT license - https://github.com/a-h/awsapigatewayv2handler/commit/eae1b0de1c53a7c7e5aceb5d7c54a6c5bdf45e12
* Added an example to the CDK of the Lambda Function URL - https://github.com/a-h/awsapigatewayv2handler/commit/e80a37e0de99bfd4b52d3f4435c5cb951caa500e

I think that should do it. Thanks again!
